<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2017 Power Kernel
 */


namespace powerkernel\billing\controllers;


use common\components\MainController;
use powerkernel\billing\models\Invoice;
use powerkernel\billing\models\Setting;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payee;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Exception\PayPalConnectionException;
use PayPal\Rest\ApiContext;
use Yii;
use yii\base\InvalidConfigException;
use yii\filters\AccessControl;
use yii\web\HttpException;

/**
 * Class PaypalController
 * @package powerkernel\billing\controllers
 */
class PaypalController extends MainController
{
    protected $apiContext = null;

    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'roles' => ['@'],
                        'allow' => true,
                    ],
                ],
            ],

        ];
    }

    /**
     * @inheritdoc
     */
    public function init()
    {
        if (\powerkernel\billing\models\Setting::getValue('paypalSandbox') == '1') {
            $client = \powerkernel\billing\models\Setting::getValue('paypalSandboxClientID');
            $secret = \powerkernel\billing\models\Setting::getValue('paypalSandboxSecret');
            $mode = 'sandbox';
        } else {
            $client = \powerkernel\billing\models\Setting::getValue('paypalClientID');
            $secret = \powerkernel\billing\models\Setting::getValue('paypalSecret');
            $mode = 'live';
        }
        if (isset($client, $secret, $mode)) {
            $this->apiContext = new ApiContext(
                new OAuthTokenCredential(
                    $client,
                    $secret
                )
            );
            $this->apiContext->setConfig([
                'mode' => $mode,
            ]);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     * @param \yii\base\Action $action
     * @return bool
     * @throws InvalidConfigException
     */
    public function beforeAction($action)
    {
        if (empty($this->apiContext)) {
            throw new InvalidConfigException(Yii::$app->getModule('billing')->t('Unable to verify Paypal API configuration.'));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * create payment
     * @param string $id
     * @return \yii\web\Response
     * @throws PayPalConnectionException
     */
    public function actionCreate($id)
    {
        $invoice = Invoice::findOne($id);
        if ($invoice->status == Invoice::STATUS_PENDING) {
            /* payer */
            $payer = new Payer();
            $payer->setPaymentMethod("paypal");

            /* payer info */


            /* items */
            $items = [];
            foreach ($invoice->items as $i => $item) {
                $items[$i] = new Item();
                $items[$i]->setName($item->name)
                    ->setCurrency($invoice->currency)
                    ->setQuantity($item->quantity)
                    //->setSku($item->id)// Similar to `item_number` in Classic API
                    ->setPrice($item->price);
            }

            /* item list */
            $itemList = new ItemList();
            $itemList->setItems($items);

            /* invoice details */
            $details = new Details();
            $details->setShipping($invoice->shipping)
                ->setTax($invoice->tax)
                ->setSubtotal($invoice->subtotal);

            $amount = new Amount();
            $amount->setCurrency($invoice->currency)
                ->setTotal($invoice->total)
                ->setDetails($details);

            /* transaction */
            $transaction = new Transaction();
            if ($email = Setting::getValue('paypalEmail')) {
                $payee = new Payee();
                $payee->setEmail($email);
                $transaction->setPayee($payee);
            }
            $transaction->setAmount($amount)
                ->setItemList($itemList)
                ->setDescription(Yii::$app->getModule('billing')->t('Invoice #' . $invoice->id_invoice))
                ->setInvoiceNumber($invoice->id_invoice);


            $urls = new RedirectUrls();
            $urls->setReturnUrl(Yii::$app->urlManager->createAbsoluteUrl(['billing/paypal/return', 'id' => (string)$invoice->id]))
                ->setCancelUrl(Yii::$app->urlManager->createAbsoluteUrl(['billing/invoice/show', 'id' => (string)$invoice->id, 'cancel' => 'true']));

            $payment = new Payment();
            $payment->setIntent('sale')
                ->setPayer($payer)
                ->setRedirectUrls($urls)
                ->setTransactions([$transaction]);

            /* call */
            try {
                $payment->create($this->apiContext);
                $approvalUrl = $payment->getApprovalLink();
                return $this->redirect($approvalUrl);
            } catch (PayPalConnectionException $ex) {
                /* send admin email */
                Yii::$app->mailer
                    ->compose()
                    ->setFrom([\common\models\Setting::getValue('outgoingMail') => Yii::$app->name])
                    ->setTo(\common\models\Setting::getValue('adminMail'))
                    ->setSubject('Paypal Error')
                    ->setTextBody(json_encode($ex->getData()))
                    ->send();
                /* redirect */
                Yii::$app->session->setFlash('error', Yii::$app->getModule('billing')->t('We can not process your payment right now.'));
                return $this->redirect(Yii::$app->urlManager->createUrl(['billing/invoice/show', 'id' => $id]));

            }


        } else {
            Yii::$app->session->setFlash('error', Yii::$app->getModule('billing')->t('We can not process your payment right now.'));
            return $this->redirect(Yii::$app->urlManager->createUrl(['billing/invoice/show', 'id' => $id]));
        }
    }


    /**
     * paypal return
     * @param string $id
     * @param string $paymentId
     * @param string $PayerID
     * @param string $token
     * @return string|\yii\web\Response
     * @throws HttpException
     */
    public function actionReturn($id, $paymentId, $PayerID, $token)
    {
        $this->layout = Yii::$app->view->theme->basePath . '/account.php';
        $invoice = Invoice::findOne($id);
        if ($invoice->status == Invoice::STATUS_PENDING) {
            if (Yii::$app->request->isPost && Yii::$app->request->post('complete')) {
                try {
                    $payment = Payment::get($paymentId, $this->apiContext);
                    /* Execution */
                    $execution = new PaymentExecution();
                    $execution->setPayerId($PayerID);
                    /* execute */
                    $result = $payment->execute($execution, $this->apiContext);
                    if (isset($result->state) && $result->state == 'approved') {
                        /* $transaction id */
                        $transactions = $payment->getTransactions();
                        $relatedResources = $transactions[0]->getRelatedResources();
                        $sale = $relatedResources[0]->getSale();
                        $saleId = $sale->getId();
                        /* update invoice */
                        $invoice->status = Invoice::STATUS_PAID;
                        $invoice->payment_method = 'Paypal';
                        $invoice->touch('payment_date');
                        $invoice->transaction = $saleId;
                        if ($invoice->save()) {
                            Yii::$app->session->setFlash('success', Yii::$app->getModule('billing')->t('Thank you for your payment. Your transaction has been completed.'));
                            unset($token);
                        } else {
                            Yii::$app->session->setFlash('error', Yii::$app->getModule('billing')->t('We can not process your payment right now.'));
                        }

                    }
                    return $this->redirect(Yii::$app->urlManager->createUrl(['billing/invoice/show', 'id' => (string)$invoice->id]));
                } catch (PayPalConnectionException  $ex) {
                    Yii::$app->session->setFlash('error', Yii::$app->getModule('billing')->t('Sorry, we cannot complete your payment at this time.'));
                    /* send error email to admin */
                    Yii::$app->mailer
                        ->compose()
                        ->setFrom([\common\models\Setting::getValue('outgoingMail') => Yii::$app->name])
                        ->setTo(\common\models\Setting::getValue('adminMail'))
                        ->setSubject('Paypal Error')
                        ->setTextBody($ex->getData())
                        ->send();
                }
            }


            return $this->render('return', ['invoice' => $invoice]);
        } else {
            Yii::$app->session->setFlash('error', Yii::$app->getModule('billing')->t('We can not process your payment right now.'));
            return $this->redirect(Yii::$app->urlManager->createUrl(['billing/invoice/show', 'id' => $id]));
        }

    }

}


