<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2017 Power Kernel
 */


namespace powerkernel\billing\widgets;

use powerkernel\billing\models\Address;
use Yii;
use yii\base\Widget;

/**
 * Class AddAddress
 * @package powerkernel\billing\widgets
 */
class AddAddress extends Widget
{

    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $model = new Address();
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            Yii::$app->controller->refresh();
        }
        return $this->render('add-address', ['model' => $model]);

    }
}