<?php

namespace powerkernel\billing\modules\api\v1;


/**
 * API module definition class
 */
class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }
}
