<?php

namespace powerkernel\billing\modules\api;


/**
 * API module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->user->enableSession = false;
        \Yii::$app->user->loginUrl = null;
        $this->modules = [
            'v1' => [
                'class' => 'powerkernel\billing\modules\api\v1\Module',
            ],
        ];
    }
}
