<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace modernkernel\billing\models;

use common\models\Account;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%billing_info}}".
 *
 * @property integer $id_account
 * @property string $company
 * @property string $tax_id
 * @property string $f_name
 * @property string $l_name
 * @property string $address
 * @property string $address2
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property string $country
 * @property string $phone
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class BillingInfo extends ActiveRecord
{


    const STATUS_ACTIVE = 10;
    const STATUS_INACTIVE = 20;


    /**
     * get status list
     * @param null $e
     * @return array
     */
    public static function getStatusOption($e = null)
    {
        $option = [
            self::STATUS_ACTIVE => Yii::$app->getModule('billing')->t('Active'),
            self::STATUS_INACTIVE => Yii::$app->getModule('billing')->t('Inactive'),
        ];
        if (is_array($e))
            foreach ($e as $i)
                unset($option[$i]);
        return $option;
    }

    /**
     * get status text
     * @return string
     */
    public function getStatusText()
    {
        $status = $this->status;
        $list = self::getStatusOption();
        if (!empty($status) && in_array($status, array_keys($list))) {
            return $list[$status];
        }
        return Yii::$app->getModule('billing')->t('Unknown');
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%billing_info}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['f_name', 'l_name', 'address', 'city', 'country', 'phone'], 'required'],
            [['id_account', 'status', 'created_at', 'updated_at'], 'integer'],
            [['company', 'tax_id', 'f_name', 'l_name', 'address', 'address2', 'city', 'state', 'zip', 'country', 'phone'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_account' => Yii::$app->getModule('billing')->t('Account'),
            'company' => Yii::$app->getModule('billing')->t('Company'),
            'tax_id' => Yii::$app->getModule('billing')->t('Tax ID'),
            'f_name' => Yii::$app->getModule('billing')->t('First Name'),
            'l_name' => Yii::$app->getModule('billing')->t('Last Name'),
            'address' => Yii::$app->getModule('billing')->t('Address'),
            'address2' => Yii::$app->getModule('billing')->t('Address 2'),
            'city' => Yii::$app->getModule('billing')->t('City'),
            'state' => Yii::$app->getModule('billing')->t('State'),
            'zip' => Yii::$app->getModule('billing')->t('Zip'),
            'country' => Yii::$app->getModule('billing')->t('Country'),
            'phone' => Yii::$app->getModule('billing')->t('Phone'),
            'status' => Yii::$app->getModule('billing')->t('Status'),
            'created_at' => Yii::$app->getModule('billing')->t('Created At'),
            'updated_at' => Yii::$app->getModule('billing')->t('Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->id_account = Yii::$app->user->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * get info, return account full name if no info
     * @param $id
     * @return array
     */
    public static function getInfo($id)
    {
        $info = [
            'company' => '',
            'tax_id' => '',
            'f_name' => '',
            'l_name' => '',
            'address' => '',
            'address2' => '',
            'city' => '',
            'state' => '',
            'zip' => '',
            'country' => '',
            'phone' => '',
        ];

        $model = BillingInfo::findOne($id);
        $account = Account::findOne($id);
        if ($model) {
            foreach ($info as $attr => $value) {
                $info[$attr] = $model->$attr;
            }
        } else {
            if ($account) {
                $info['f_name'] = $account->fullname;
            }
        }


        $info['email'] = $account->email;
        return $info;
    }
}
