<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace modernkernel\billing\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%billing_item}}".
 *
 * @property integer $id
 * @property string $id_invoice
 * @property string $name
 * @property integer $quantity
 * @property string $price
 * @property string $details
 *
 * @property Invoice $invoice
 */
class Item extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%billing_item}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_invoice', 'name'], 'required'],
            [['id', 'quantity'], 'integer'],
            [['price'], 'number'],
            [['details'], 'string'],
            [['id_invoice'], 'string', 'max' => 23],
            [['name'], 'string', 'max' => 255],
            [['id_invoice'], 'exist', 'skipOnError' => true, 'targetClass' => Invoice::className(), 'targetAttribute' => ['id_invoice' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::$app->getModule('billing')->t('ID'),
            'id_invoice' => Yii::$app->getModule('billing')->t('Invoice'),
            'name' => Yii::$app->getModule('billing')->t('Name'),
            'quantity' => Yii::$app->getModule('billing')->t('Quantity'),
            'price' => Yii::$app->getModule('billing')->t('Price'),
            'details' => Yii::$app->getModule('billing')->t('Details'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(Invoice::className(), ['id' => 'id_invoice']);
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        $this->invoice->calculate();
        $this->invoice->save(false);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
